start_from = "teacher"
reset_optimizer = false

[paths]
base_model = "div_4.safetensors"
checkpoint_output = ""
dataset_name = "test"
comfy_dir = "/home/okolenmi/comfy/ComfyUI/"

[common]
steps = 200
batch_size = 2
grad_accum = 32
lr = 0.0001
optimizer = "xpu-adafactor"
adafactor_scale_param = false
seed = 48
save_every = 0
lr_schedule = "cosine"
lr_end = 1e-05
lr_power = 2.0
lr_warmup_steps = 0
lr_warmup_start = 0.0
lr_strategy = "uniform"
center_mult = 0.67
side_mult = 1.5
time_mult = 1.8
snr_weighting = "inverse_snr"
t_mode = "uniform"
t_low = 0
t_high = 999
device = "xpu"
no_compile = true
no_checkpoint = true
dump_cache_samples = false
save_on_crash = true
data_source = "dataset"
teacher_type = "eps"
student_type = "eps"
resume_step = 0
latent_size = 0
use_dataset_cfg = false
training_positive_prompt = ""
training_negative_prompt = ""
pre_cond_enable = false
pre_cond_power_min = 0.1
pre_cond_power_max = 0.5
pre_cond_clean_ratio = 0.3

[tuning]
method = "lora"
rank = 96
alpha = 64.0
dropout = 0.0
lora_output = "test_lora10m.safetensors"
target_all = false
block_weighting = ""
gate_enabled = false
gate_train_low = 0.0
gate_train_high = 999.0
gate_width = 10.0

[cache]
mode = "trajectory"
batch_size = 0
traj_steps_min = 20
traj_steps_max = 30
traj_skip_steps = 4
sequence_size = 0
sequence_mode = "random"
cfg = 4.0
cfg_random = false
cfg_min = 1.0
cfg_max = 1.0
cond_mode = "random"
positive_prompt = ""
negative_prompt = ""
student_mix = 0.0
student_anchor_steps = 5
student_chain_len = 3
student_chain_noise = 0.02

[preview]
enabled = true
every_n_steps = 100
prompts = "landscape\r\ncozy room\r\n2 girls eating"
negative_prompt = ""
steps = 24
cfg = 6.0
resolution = 768
seed = 1
max_batch_size = 8
