start_from = "teacher"
reset_optimizer = false

[paths]
base_model = "models/checkpoints/divergence_3.safetensors"
checkpoint_output = ""
dataset_name = "test"
comfy_dir = "/home/okolenmi/comfy/ComfyUI/"

[common]
steps = 20000
batch_size = 1
grad_accum = 7
lr = 1.5e-05
optimizer = "xpu-adafactor"
adafactor_scale_param = false
seed = 48
save_every = 0
lr_schedule = "cosine"
lr_end = 1e-05
lr_power = 2.0
lr_warmup_steps = 0
lr_warmup_start = 0.0
lr_strategy = "uniform"
center_mult = 0.67
side_mult = 1.5
time_mult = 1.8
snr_weighting = "decay_snr"
t_mode = "uniform"
t_low = 0
t_high = 999
device = "xpu"
no_compile = true
no_checkpoint = true
dump_cache_samples = false
save_on_crash = true
data_source = "dataset"
teacher_type = "eps"
student_type = "eps"
resume_step = 0
latent_size = 0
cfg_aware = true
training_cfg_min = 1.0
training_cfg_max = 9.0
training_positive_prompt = ""
training_negative_prompt = ""
pre_cond_enable = false
pre_cond_power_min = 0.1
pre_cond_power_max = 0.5
pre_cond_clean_ratio = 0.3

[tuning]
method = "lora"
rank = 128
alpha = 64.0
dropout = 0.0
lora_output = "models/loras/test_lora10f.safetensors"
target_all = false
lora_continue_from = "models/loras/test_lora10e.safetensors"
block_weighting = "input_blocks.0:0.3, input_blocks.1:0.7, input_blocks.2:0.5, input_blocks.3:0.6, input_blocks.4:0.9, input_blocks.5:0.9, input_blocks.6:0.9, input_blocks.7:0.9, input_blocks.8:0.5, middle_block:0.3, output_blocks.0:0.3, output_blocks.1:0.4, output_blocks.2:0.9, output_blocks.3:0.9, output_blocks.4:0.8, output_blocks.5:0.7, output_blocks.6:0.6, output_blocks.7:0.5, output_blocks.8:0.5, time_embed:0.0, label_emb:0.5, out:0.2"

[cache]
mode = "trajectory"
batch_size = 0
traj_steps_min = 20
traj_steps_max = 30
traj_skip_steps = 4
sequence_size = 0
sequence_mode = "random"
cfg = 4.0
cond_mode = "random"
positive_prompt = ""
negative_prompt = ""
student_mix = 0.0
student_anchor_steps = 5
student_chain_len = 3
student_chain_noise = 0.02
